### ISSUE TITLE
Configure highlighting

### ISSUE THREAD

**Issue by agirorn** [posva/vim-vue#21] opened 2016-07-24 12:39 UTC
Is there any way to configure what javascript syntax highlighting is being used?

I for one have configured my vim to use [jelera/vim-javascript-syntax](https://github.com/jelera/vim-javascript-syntax) for javascript insted of the default javascript and I'd like to use the same inside of vue.

**Comment by posva** [comment] 2016-07-24 16:51
It should be using the last one registered. Isn't that what's happening?

**Comment by agirorn** [comment] 2016-07-25 12:49
Almost, except for a global function that is for some reason not done correctly. And this might be a configuration issue on my part. I just don't know how to debug it any further.

![image](https://cloud.githubusercontent.com/assets/261378/17101580/ef4c5142-5264-11e6-86bf-944822b09a35.png)

The blue function is taged as `hi<javaScriptFuncKeyword> trans<javaScriptFuncKeyword> lo<Function>``

while the read function is taged `hi<javaScriptGlobalObjects> trans<javaScriptGlobalObjects> lo<Special>`

According to my configuration, it should be blue.

**Comment by JuanVqz** [comment] 2016-08-17 02:22
Hi thanks for your help.

I have the problem that the html syntax discolour.

![vim-vue](https://cloud.githubusercontent.com/assets/7331511/17722390/6bbc83d4-63f7-11e6-96b1-151a9f43c9aa.png)

Do you know how to fix it? Beforehand thank you very much!

**Comment by agirorn** [comment] 2016-08-17 10:38
I never found out why this is happening and have accepted this highlighting for now.

**Comment by JuanVqz** [comment] 2016-08-17 12:20
Thanks agirom!

**Comment by mixedCase** [comment] 2016-09-11 19:42
I can confirm that this bug only occurs with [jelera/vim-javascript-syntax](https://github.com/jelera/vim-javascript-syntax). 

Which is the only syntax highlighter that works well in my experience. [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) works too but they don't support inlined indentation so that ruins it.

**Comment by agirorn** [comment] 2016-09-11 20:52
@mixedCase do you know if this needs to be fixed int vim-vue or in jelera/vim-javascript-syntax ?

**Comment by mixedCase** [comment] 2016-09-11 21:01
@agirorn No clue. Tried looking at both syntaxes' respective source codes as well as mixing and matching loading functions and found no difference.

Then again I'm no Vim plugin expert. In the meantime I'm putting up with shitty syntax highlighting. Btw @posva, which syntax highlighting plugin do you use?

**Comment by posva** [comment] 2016-09-11 21:04
I use pangloss/vim-javascript

**Comment by mixedCase** [comment] 2016-09-11 21:05
@posva How do you fix its broken indenting?

**Comment by posva** [comment] 2016-09-11 22:12
Well, it works 😕

**Comment by mixedCase** [comment] 2016-09-11 22:21
@posva With ES6 code? Don't your import lines or export statement backtrack misalign?

I've tried running it with a clean init.vim and disabling all plugins but itself and vim-vue and it doesn't work. Indentation is just plain wrong.

**Comment by posva** [comment] 2016-09-12 07:31
yeah, here's the full list of my plugins. I haven't updated it in a while so there may be duplicates

``` viml
" Init options for vundle {
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" }

" Vundle and main plugins {
Plugin 'gmarik/Vundle.vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
" }

" Editing & Utils {
Plugin 'tpope/vim-repeat'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'tomtom/tcomment_vim'
Plugin 'rking/ag.vim'
Plugin 'tikhomirov/vim-glsl'
Plugin 'FredKSchott/CoVim'
Plugin 'kyuhi/vim-emoji-complete'
" }

" Latex {
Plugin 'lervag/vimtex'
" }

" Mines {
"Plugin 'posva/Rndm'
"Plugin 'vim-scripts/Mines'
" }

" Colorschemes/Themes {
Plugin 'croaker/mustang-vim'
Plugin 'fmoralesc/vim-vitamins'
Plugin 'flazz/vim-colorschemes'
Plugin 'chriskempson/tomorrow-theme'
Plugin 'jaxbot/semantic-highlight.vim'
"Plugin 'altercation/vim-colors-solarized'
"Plugin 'spf13/vim-colors'
" }

" Align text with tabular {
Plugin 'godlygeek/tabular'
" }

" Sessions are good {
Plugin 'vim-scripts/sessionman.vim'
" }

" Airline iformation about the file at bottom {
"Plugin 'bling/vim-airline'
Plugin 'itchyny/lightline.vim'
Plugin 'ryanoasis/vim-devicons'
" }

" Javascript {
Plugin 'elzr/vim-json'
"Plugin 'groenewege/vim-less'
Plugin 'pangloss/vim-javascript' " indentation and syntax support
Plugin 'briancollins/vim-jst' " indenting and highlighting jst/ejs
Plugin 'kchmck/vim-coffee-script'
Plugin 'mtscout6/vim-cjsx'
Plugin 'maksimr/vim-jsbeautify'
Plugin 'einars/js-beautify'
Plugin 'heavenshell/vim-jsdoc'
" }

" HTML {
Plugin 'mattn/emmet-vim'
"Plugin 'amirh/HTML-AutoCloseTag'
Plugin 'othree/html5.vim'
Plugin 'wavded/vim-stylus'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'tpope/vim-haml'
Plugin 'digitaltoad/vim-pug'
Plugin 'posva/vim-vue'
" }

" PHP {
"Plugin 'spf13/PIV'
"Plugin 'arnaud-lb/vim-php-namespace'
" }

" Scala {
Plugin 'derekwyatt/vim-scala'
" }

" Autoclose brackets, etc Press <C-c> for new line {
"Plugin 'spf13/vim-autoclose'
" }

" Autocompletion {
if has("lua") && v:version >= 740
  Plugin 'Shougo/neocomplete.vim'
  Plugin 'Shougo/neosnippet'
  Plugin 'Shougo/neosnippet-snippets'
  Plugin 'honza/vim-snippets'
endif
" }

" TagBar (ctags, jsctags, etc) {
if v:version >= 702
  Plugin 'majutsushi/tagbar'
endif
" }

" Indent guide plugin {
if exists('*matchadd')
  Plugin 'nathanaelkane/vim-indent-guides'
endif
" }

" Syntastic plugin for compilation errors {
Plugin 'scrooloose/syntastic'
" }

" Gundo {
Plugin 'sjl/gundo.vim'
" }

" git  {
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
" }

" Java IDE {
"Plugin 'vim-scripts/Vim-JDE'
"Plugin 'vim-scripts/javacomplete'
" }

" NERD Tree {
Plugin 'scrooloose/nerdtree'
" }

" NERD commenter {
Plugin 'scrooloose/nerdcommenter'
" }

" Markdown {
Plugin 'plasticboy/vim-markdown'
" }

" Surrounding, just awesome {
Plugin 'tpope/vim-surround'
" }

" Cool surronding character coloring
Plugin 'kien/rainbow_parentheses.vim'

" ST like functionalities {
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'terryma/vim-multiple-cursors'
" }

" numbers: better line numbers {
if v:version >= 730
  Plugin 'myusuf3/numbers.vim'
endif
"}

" A plugin for automatically restoring file's cursor position and folding
Plugin 'vim-scripts/restore_view.vim'

" Autocompletion {
"Plugin 'Valloric/YouCompleteMe'
" }

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
```

**Comment by mixedCase** [comment] 2016-09-12 15:28
@posva Could you try indenting this and post back what you got? https://gist.github.com/mixedCase/7e18a29bd3226a280ef0acd4ebe93143

I've gone through your dotfiles, tried a lot of mixing and matching but no dice.

**Comment by posva** [comment] 2016-09-12 15:46
@mixedCase You are right. It doesn't work 😓 
I get the same exact output. What I usually do it manually indent some specific lines and then only indent few lines at the same time. This way it uses the previous indentation. It's still not working on es6 features thought 😕

**Comment by psi-4ward** [comment] 2016-10-17 14:20
So anyone has scss highlight working?

**Comment by mixedCase** [comment] 2016-10-17 16:29
@psi-4ward Yes, I'm using `ohtree/html5.vim` and `hail2u/vim-css3-syntax`. Make sure to start your style block with `<style lang="scss">`.

**Comment by sliceofcode** [comment] 2016-12-06 01:40
`<script>` tag highlighting doesn't work for [yajs.vim](https://github.com/othree/yajs.vim), either. I think the `<script>` tag is being highlighted by the JavaScript syntax, I'm not sure.

**Comment by sliceofcode** [comment] 2017-01-08 15:37
Okay, I think I got a fix.

Change line 59 of `syntax/vue.vim` to this:
```vim
syntax region javascript keepend matchgroup=Delimiter start=/<script\( lang="babel"\)\?\( type="text\/babel"\)\?>/ end="</script>" contains=@JS fold
```

This fixes JavaScript highlighting for me (I use `yajs.vim`)

Before:
![20170108_072240_nwa](https://cloud.githubusercontent.com/assets/4206232/21751027/18a2c1be-d575-11e6-8ea4-8826d070177e.png)

After:
![20170108_073631_jzo](https://cloud.githubusercontent.com/assets/4206232/21751039/30d34ec0-d575-11e6-9443-5c266b1a92c7.png)

Enjoy! :) @posva Should I make a PR for this? I don't know if this breaks stuff, I still need feedback from others

**Comment by posva** [comment] 2017-01-08 22:33
@sliceofcode Tested it and seems to work nicely 🙂 . Yes, please, go ahead and open a PR
@agirorn can you test locally that change and tell us if it fixes the issue?

**Comment by sliceofcode** [comment] 2017-01-09 05:46
Here you go: #43

Maybe we should wait for feedback first.

**Comment by jacoborus** [comment] 2017-01-09 08:23
It works for me too

**Comment by posva** [comment] 2017-01-09 09:52
Closed by d90cd7b

**Closed by posva** 2017-01-09 09:52 UTC
Labels: help wanted

**Comment by avral** [comment] 2017-02-05 17:08
Not work for me :(
<img width="703" alt="screen shot 2017-02-05 at 20 07 39" src="https://cloud.githubusercontent.com/assets/10092436/22628085/ca9259d2-ebde-11e6-95ce-def07e4757a1.png">

**Comment by posva** [comment] 2017-02-05 17:31
Tested with Vim 8 and works nicely

**Comment by avral** [comment] 2017-02-05 17:53
NVIM 0.1.7

**Comment by posva** [comment] 2017-02-05 18:26
In that case you may want to seach there for issues about compound filetypes

**Comment by sliceofcode** [comment] 2017-02-18 23:12
Hmm, I am using Neovim and I am experiencing the same problems as @avral. I'll try to investigate
