### ISSUE TITLE
  Why not prompt completion

### ISSUE THREAD

**Issue by Sinnoo** [posva/vim-vue#81] opened 2017-08-04 06:44 UTC
Why not prompt completion

**Comment by posva** [comment] 2017-08-04 06:58
Can you give more details, please?

**Comment by HerringtonDarkholme** [comment] 2017-09-07 05:18
OP probably wants omnifunction or completion source for neocomplete/youcompleteme/deoplete.

I think this request is out of scope of this plugin.

I recommend https://github.com/autozimu/LanguageClient-neovim and https://github.com/vuejs/vetur/tree/master/server 

(Or VSCode VIm)

**Comment by posva** [comment] 2017-09-07 09:54
I see, thanks for the heads up @HerringtonDarkholme 🙂

**Closed by posva** 2017-09-07 09:54 UTC

**Comment by matsp** [comment] 2018-02-13 18:25
@posva or @HerringtonDarkholme you actually have a working solution in vim for auto-completition? I'm struggling around to get the vue-language-server proberly working. Actually just the template auto-complete works together with deoplete.

**Comment by HerringtonDarkholme** [comment] 2018-02-14 01:12
@matsp can you try the latest vls? 
 If that still doesn't work, please give a repro.

**Comment by matsp** [comment] 2018-02-14 07:59
> @matsp can you try the latest vls?
> If that still doesn't work, please give a repro.

I just installed vue-language-server as global package so it must be the newest one.
Just see that you are one of the main contributors of the vetur repo ;-)
Would be nice if you have the time to help out - maybe at another place.

Here is my working *template* region:

![vue-html-region](https://user-images.githubusercontent.com/2205242/36192928-11393e36-1164-11e8-99ca-6be495a50f8f.gif)

The *script* region is actually not working for me:

![vue-script-region](https://user-images.githubusercontent.com/2205242/36192930-1155fe22-1164-11e8-96d5-9bdf5367fc9d.gif)

My neovim [init.vim](https://github.com/matsp/dotfiles/blob/master/.config/nvim/init.vim) is not very complex but might be misconfigured somehow.

Thanks for the help @HerringtonDarkholme.

**Comment by HerringtonDarkholme** [comment] 2018-02-14 08:11
![screen shot 2018-02-14 at 4 10 19 pm](https://user-images.githubusercontent.com/2883231/36193641-a1b18828-11a1-11e8-92a1-971801671053.png)

Can you reproduce it in https://github.com/octref/veturpack ?

Note, props starting with `$` won't get completion due to keyword pattern.

**Comment by matsp** [comment] 2018-02-14 08:20
![bildschirmfoto vom 2018-02-14 09-17-33](https://user-images.githubusercontent.com/2205242/36193903-f0a84b2c-1167-11e8-8ecb-49d05f30109a.png)

Nope, seems that the region will not be detected as javascript or something in that direction.

**Comment by HerringtonDarkholme** [comment] 2018-02-14 08:22
![screen shot 2018-02-14 at 4 21 26 pm](https://user-images.githubusercontent.com/2883231/36194035-260f78a4-11a3-11e8-9d7f-b95fda7c679a.png)

**Comment by matsp** [comment] 2018-02-14 08:49
Is this done by your vim-typescript code additions?

**Comment by HerringtonDarkholme** [comment] 2018-02-14 08:50
It only relies on vim-vue and Langauge Server client

**Comment by matsp** [comment] 2018-02-14 09:15
Mhm tried to setup like your neovim. Comment out all other syntax plugins etc. but still no LC completion - just the fields in the file.

**Comment by ismatim** [comment] 2018-07-21 01:15
@matsp: Why is this close ? Did you resolve it ?

**Comment by matsp** [comment] 2018-07-21 06:33
@ismatim I commented on an already closed issue :wink: I've got resolved it by starting a totally blank config with only the vls.

**Comment by ismatim** [comment] 2018-07-22 00:39
@matsp 👍 thanks.
I was having a conflict with the mapping: `autocmd BufRead,BufNewFile *.vue setlocal filetype=vue.html.javascript.css` when I checked the log from LanguageClient.
